<a href="https://colab.research.google.com/github/SONGZERUIgit/POLITO_MACHINE_LEARNING/blob/main/kmeans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [64]:
def kmeans(data,k,maxIter):
  center=initial(data,k)
  for _ in range(maxIter):
    cluster=fenpei(data,center)
    center1=center
    center=np.array(data)[new_center(data,cluster,k)]
  return cluster

In [66]:
import random
def initial(data,k):
  num=[]
  data=np.array(data)
  for i in range(len(data)):
    num.append(i)
  centers=random.sample(num,k)
  return data[centers]


In [67]:
def fenpei(data,center):
  res=[]
  for i in range(len(data)):
    dis=[]
    for j in range(len(center)):
      dis.append(distance(data[i],center[j]))
    index=dis.index(min(dis))
    res.append(index)
  return res

In [68]:
def distance(data1,data2):
  dis=0
  for i in range(len(data1)):
    dis+=pow((data1[i]-data2[i]),2)
  return np.sqrt(dis)


In [79]:
def new_center(data,cluster,k):
  data=np.array(data)
  center=[]
  for i in range(k):
    temp=np.where(np.array(cluster)==i)
    res=data[temp]
    center1=compare(res)
    center.append(center1)
  return center





In [77]:
def compare(data):
  a=len(data)
  temp=np.zeros([a,a])
  for i in range(a):
    for j in range(a):
      temp[i,j]=distance(data[i],data[j])
  res=[]
  for i in range(a):
    res.append(np.mean(temp[i]))
  index=np.where(np.array(res)==min(res))
  index=index[0][0]
  return index

In [52]:
data=[[1,2],[4,6],[11,1],[20,1]]

array([2])

[2]

(array([0, 2]),)

False

In [84]:
kmeans(data,2,100)

[0, 1, 1, 1]

[1, 1, 0, 0]

array([[11,  1],
       [ 1,  2]])